//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Miniatuurland
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetails
    {
        public int orderID { get; set; }
        public int productID { get; set; }
        public Nullable<short> quantityOrdered { get; set; }
        public Nullable<decimal> priceEach { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Products Products { get; set; }
    }
}
